### ISSUE TITLE
Bump Bazel 8 version to 8.0.0rc2/make it configurable

### ISSUE THREAD

**Issue by sin-ack** [bazel-contrib/.github#18]
Bazel 8.0.0rc1 has an issue with `protobuf`, and fails to run tests in CI for me:

```
» USE_BAZEL_VERSION=8.0.0rc1 bazel test //...                                                                                                                                                                3 ↵
2024/11/04 13:45:13 Downloading https://releases.bazel.build/8.0.0/rc1/bazel-8.0.0rc1-linux-x86_64...
Downloading: 60 MB out of 60 MB (100%) 
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'protobuf' found. This will result in a failure if there's a reference to those rules or symbols.
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
ERROR: Traceback (most recent call last):
	File "/home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/src/google/protobuf/compiler/BUILD.bazel", line 234, column 13, in <toplevel>
		aarch64_test(
	File "/home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/build_defs/arch_tests.bzl", line 44, column 20, in aarch64_test
		_arch_test_impl(
	File "/home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/build_defs/arch_tests.bzl", line 23, column 19, in _arch_test_impl
		inline_sh_test(
	File "/home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/build_defs/internal_shell.bzl", line 89, column 11, in inline_sh_test
		native.sh_test(
Error: no native function or rule 'sh_test'
Available attributes: action_listener, alias, available_xcodes, cc_binary, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_shared_library, cc_static_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_plugins_flag_alias, java_proto_library, java_runtime, java_test, java_toolchain, label_flag, label_setting, legacy_globals, memprof_profile, module_name, module_version, objc_import, objc_library, package, package_group, package_name, package_relative_label, platform, propeller_optimize, proto_lang_toolchain, proto_library, repo_name, repository_name, starlark_doc_extract, subpackages, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
ERROR: /home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/src/google/protobuf/compiler/BUILD.bazel:178:11: Cannot compute config conditions
ERROR: /home/agni/.cache/bazel/_bazel_agni/0687462a0a4f1c0c15b193502f55c39f/external/protobuf+/BUILD.bazel:222:10: Target '@@protobuf+//src/google/protobuf/compiler:protoc_lib' contains an error and its package is in error and referenced by '@@protobuf+//:protoc'
```

Bazel 8.0.0rc2 does not exhibit this problem. It would be cool if there was a way to force the versions to be used so that we can update this from our side. For now I disabled 8.0.0rc1 tests completely.

**Comment by sin-ack** [comment]
Fixed with 646899086d7aaee8e532540480f3e91e00596234.
